[package]
name = "test-parser"
version = "0.1.0"
authors = ["Ben Doan <ben@bendoan.me>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.0"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.16.0"

