[package]
name = "chat_system"
version = "0.1.0"
authors = ["Ben Doan <ben@bendoan.me>"]

[dependencies]
cursive = "0.7"
serde = "1.0.17"
serde_derive = "1.0.5"
serde_json = "1.0.5"

[lib]
name = "chatlib"
path = "src/lib.rs"

[[bin]]
name = "chatbin"
path = "src/bin/main.rs"
